Repository worldcoin/orb-software, pull requests merged in 2024-10, with the labels that each got.

#247 fix: nicer error message when mandatory args are missing.
  hil/src/commands/flash.rs
Labels: trivial

#244 orb-ui: use Duration::ZERO instead of Option<Duration>
  orb-ui/sound/src/queue.rs
  orb-ui/src/engine/diamond.rs
  orb-ui/src/engine/pearl.rs
  orb-ui/src/sound/mod.rs
Labels: difficulty:trivial

#260 ci: add OpenSSL to allowed licenses
  deny.toml
Labels: difficulty:trivial

#253 hil: Use multi-part download for hil
  hil/src/download_s3.rs
Labels: blocked:author

#256 zbus-proxies: add login1 proxy
  Cargo.lock
  Cargo.toml
  nix/shells/development.nix
  update-verifier/Cargo.toml
  zbus-proxies/Cargo.toml
  zbus-proxies/cli/Cargo.toml
  zbus-proxies/cli/README.md
  zbus-proxies/cli/build.rs
  zbus-proxies/cli/src/main.rs
  zbus-proxies/src/generated/README.md
  zbus-proxies/src/lib.rs
  zbus-proxies/src/login1/mod.rs
  zbus-proxies/src/login1/shutdown.rs
  zbus-proxies/src/tweaked/README.md
  zbus-proxies/src/tweaked/login1.rs
  zbus-proxies/xml/README.md
  zbus-proxies/xml/login1.xml
Labels: blocked:reviewer

#266 orb-ui: increased volume to ask for wifi
  ui/src/engine/diamond.rs
  ui/src/engine/pearl.rs
  ui/src/sound/mod.rs
Labels: difficulty:trivial, blocked:reviewer
