Repository worldcoin/orb-software, pull requests merged in 2024-11, with the labels that each got.

#267 chore(orb-ui): animation for wifi qr code scanning in self-serve
  ui/rgb/src/lib.rs
  ui/src/engine/diamond.rs
  ui/src/engine/pearl/self_serve.rs
  ui/src/simulation.rs
Labels: tested:yes

#258 telemetry: introduce orb-telemetry crate and use it in orb-ui
  Cargo.lock
  Cargo.toml
  telemetry/Cargo.toml
  telemetry/src/lib.rs
  ui/Cargo.toml
  ui/examples/ui-replay.rs
  ui/src/main.rs
Labels: difficulty:nontrivial, tested:no

#231 utils: generation of new orb-ids && registration support
  scripts/generate-new-orb-id/build/.gitignore
  scripts/generate-new-orb-id/build/calibration.json
  scripts/generate-new-orb-id/build/components.json
  scripts/generate-new-orb-id/build/versions.json
  scripts/generate-new-orb-id/gen-orb-id.sh
Labels: blocked:reviewer

#246 slot-ctrl: remove two lines of unsafe
  Cargo.lock
  Cargo.toml
  slot-ctrl/Cargo.toml
  slot-ctrl/src/efivar/mod.rs
  slot-ctrl/src/program.rs
Labels: difficulty:trivial

#290 fix: remove clang override for stdenv and switch runner to unstable
  nix/machines/hil-common.nix
  nix/packages/hil.nix
  nix/shells/development.nix
Labels: tested:yes, blocked:reviewer
