Repository worldcoin/orb-software, pull requests merged in 2025-03, with the labels that each got.

#393 feat(gst-jpeg): hardware-accelerated jpg encode
  Cargo.lock
  Cargo.toml
  deny.toml
  gst-jpeg/Cargo.toml
  gst-jpeg/README.md
  gst-jpeg/src/lib.rs
  nix/shells/development.nix
Labels: tested:yes, blocked:reviewer

#391 feat(fleet-cmdr): FM-383-fleet-cmdr-job-integration
  Cargo.lock
  fleet-cmdr/Cargo.toml
  fleet-cmdr/README.md
  fleet-cmdr/debian/fleet-cmdr.worldcoin-fleet-cmdr.service
  fleet-cmdr/src/args.rs
  fleet-cmdr/src/handlers/cmd_orb_details.rs
  fleet-cmdr/src/handlers/cmd_reboot.rs
  fleet-cmdr/src/handlers/mod.rs
  fleet-cmdr/src/job_client.rs
  fleet-cmdr/src/lib.rs
  fleet-cmdr/src/main.rs
  fleet-cmdr/src/orb_info.rs
Labels: blocked:reviewer

#435 feat(s3-helpers): implement list_prefix
  .github/workflows/rust-ci.yaml
  Cargo.lock
  Cargo.toml
  hil/Cargo.toml
  hil/src/download_s3.rs
  nix/shells/development.nix
  s3-helpers/Cargo.toml
  s3-helpers/README.md
  s3-helpers/examples/list.rs
  s3-helpers/src/client.rs
  s3-helpers/src/lib.rs
  s3-helpers/src/list_prefix.rs
  s3-helpers/src/s3_url_parts.rs
  s3-helpers/tests/common/mod.rs
  s3-helpers/tests/list_prefix.rs
Labels: difficulty:nontrivial, tested:yes, blocked:reviewer

#436 feat(s3-helpers): make multipart_download general and test it
  Cargo.lock
  Cargo.toml
  hil/Cargo.toml
  hil/src/commands/flash.rs
  hil/src/download_s3.rs
  s3-helpers/Cargo.toml
  s3-helpers/examples/list.rs
  s3-helpers/src/client.rs
  s3-helpers/src/download.rs
  s3-helpers/src/lib.rs
  s3-helpers/src/list_prefix.rs
  s3-helpers/tests/common/mod.rs
  s3-helpers/tests/common_tests.rs
  s3-helpers/tests/download_multipart.rs
  s3-helpers/tests/list_prefix.rs
Labels: difficulty:nontrivial, tested:yes

#442 feat(bidiff-squashfs): implement diffing plan, clean up fetching
  Cargo.lock
  Cargo.toml
  bidiff-squashfs/cli/Cargo.toml
  bidiff-squashfs/cli/src/diff_ota.rs
  bidiff-squashfs/cli/src/diff_plan.rs
  bidiff-squashfs/cli/src/fetch.rs
  bidiff-squashfs/cli/src/lib.rs
  bidiff-squashfs/cli/src/main.rs
  s3-helpers/src/client.rs
  s3-helpers/src/lib.rs
  s3-helpers/src/list_prefix.rs
  s3-helpers/src/s3_uri.rs
  update-agent/core/src/claim.rs
  update-agent/core/src/file_location.rs
Labels: difficulty:nontrivial, tested:yes

#392 feat(arc-pool): initial commit
  Cargo.lock
  Cargo.toml
  arc-pool/Cargo.toml
  arc-pool/README.md
  arc-pool/src/lib.rs
Labels: tested:yes, blocked:reviewer

#388 refactor(wt-video): turn into reusable crate
  Cargo.lock
  Cargo.toml
  experiments/webtransport_video/src/main.rs
  experiments/webtransport_video/src/networking.rs
  wt-video/Cargo.toml
  wt-video/README.md
  wt-video/examples/rainbow/main.rs
  wt-video/examples/rainbow/video.rs
  wt-video/index.html
  wt-video/index.js
  wt-video/screenshot.png
  wt-video/src/control.rs
  wt-video/src/http_server.rs
  wt-video/src/lib.rs
  wt-video/src/wt_server.rs
Labels: tested:yes, blocked:reviewer
