Repository worldcoin/orb-software, pull requests merged in 2025-04, with the labels that each got.

#461 refactor(update-agent): get rid of gpt fork and TakePartition
  Cargo.lock
  Cargo.toml
  update-agent/Cargo.toml
  update-agent/core/src/components.rs
  update-agent/src/update/can.rs
  update-agent/src/update/capsule.rs
  update-agent/src/update/gpt.rs
  update-agent/src/update/mod.rs
  update-agent/src/update/raw.rs
  update-agent/tests/main.rs
Labels: tested:yes

#463 feat(ui): Pearl biometric-flow UX
  ui/src/engine/animations/composites/biometric_flow.rs
  ui/src/engine/animations/composites/mod.rs
  ui/src/engine/animations/fake_progress_v2.rs
  ui/src/engine/animations/mod.rs
  ui/src/engine/animations/progress.rs
  ui/src/engine/diamond.rs
  ui/src/engine/mod.rs
  ui/src/engine/pearl/self_serve.rs
Labels: tested:yes

#493 feat(hil): allow user to pass --timeout to login command
  hil/src/commands/login.rs
Labels: blocked:author

#503 feat(bidiff-cli): support prod account
  bidiff-cli/src/fetch.rs
  bidiff-cli/src/lib.rs
  bidiff-cli/src/ota_path.rs
  docs/src/SUMMARY.md
  docs/src/aws-creds.md
  docs/src/hil/cli.md
  s3-helpers/src/client.rs
Labels: tested:no, ai:none

#501 feat(ota-backend): scaffold out hello world
  .dockerignore
  Cargo.lock
  Cargo.toml
  ota-backend/Cargo.lock
  ota-backend/Cargo.toml
  ota-backend/Dockerfile
  ota-backend/build.rs
  ota-backend/docker-compose.yml
  ota-backend/migrations/20240423100000_initial.sql
  ota-backend/src/app.rs
  ota-backend/src/db.rs
  ota-backend/src/lib.rs
  ota-backend/src/main.rs
  ota-backend/tests/app.rs
  ota-backend/tests/db.rs
Labels: tested:yes, ai:vibe
